spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/blog-api}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false

  jackson:
    deserialization:
      fail-on-unknown-properties: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET:EAiK+3p5RYGXRB8Uol1ct7BE4pWZnozzNaFsjiUDjJE=}
  expiration: ${JWT_EXPIRATION:3600000}

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework: WARN
    br.com.blog.api: DEBUG